[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "ManifestConverter"
description = "A ludusavi manifest converter for SaveManager"
version = "0.1.0"
languages = ["C", "CXX"]
msvc-runtime = "dynamic"

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true
CMAKE_BUILD_TYPE = "Release"

[fetch-content.curl]
git = "https://github.com/curl/curl"
tag = "curl-8_21_0"

[fetch-content.nlohmann_json]
git = "https://github.com/nlohmann/json"
tag = "v3.12.0"

[fetch-content.yaml-cpp]
git = "https://github.com/jbeder/yaml-cpp"
tag = "yaml-cpp-0.9.0"

[target.fetcher]
type = "executable"
sources = ["src/fetcher/**.cpp", "src/fetcher/**.hpp"]
include-directories = ["src/fetcher/"]
compile-features = ["cxx_std_23"]
precompile-headers = ["src/pch.hpp"]
link-libraries = ["nlohmann_json::nlohmann_json", "CURL::libcurl"]

[target.converter]
type = "executable"
sources = ["src/converter/**.cpp"]
compile-features = ["cxx_std_23"]
precompile-headers = ["src/pch.hpp"]
link-libraries = ["nlohmann_json::nlohmann_json", "yaml-cpp::yaml-cpp"]
