name: Fetch & Convert Ludusavi's manifest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: lfc
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  fetch_and_convert_manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4

      - name: Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: build
          key: build-${{ hashFiles('cmake.toml', 'CMakeLists.txt', 'src/**') }}

      - name: Install GCC 14
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-14

      - name: Build Fetcher & Converter
        run: |
          cmake -B build --fresh -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14
          cmake --build build --config Release -j

      - name: Fetch Manifest
        run: |
          if ! timeout 18000 ./build/fetcher; then
            status=$?
            if [ "$status" -eq 124 ]; then
              echo "Fetcher timed out after 18000 seconds."
            else
              echo "Fetcher exited with code $status."
            fi
            exit 1
          fi

      - name: Convert Manifest
        run: ./build/converter

      - name: Commit progress
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/manifest.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            git commit -m "Fetch latest manifest changes @ ($timestamp)"
            git push
          fi
